# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1327855086);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1327855206);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1327855326);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "http://www.trendsigma.net/vmware/");
user_pref("browser.startup.homepage_override.buildID", "20111008085056");
user_pref("browser.startup.homepage_override.mstone", "rv:7.0.1");
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.event.contextmenu.enabled", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 5);
user_pref("extensions.enabledAddons", "langpack-en-ZA@firefox.mozilla.org:7.0.1,langpack-en-GB@firefox.mozilla.org:7.0.1,globalmenu@ubuntu.com:2.0.1,ubufox@ubuntu.com:1.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:7.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1318587857000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1318078360000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1318587479000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1318078360000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/globalmenu@ubuntu.com\",\"mtime\":1318587483000}}}]");
user_pref("extensions.lastAppVersion", "7.0.1");
user_pref("extensions.lastPlatformVersion", "7.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.update.enabled", false);
user_pref("font.default.x-western", "sans-serif");
user_pref("font.size.fixed.x-western", 16);
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d10", 3);
user_pref("gfx.blacklist.layers.direct3d10-1", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("gfx.blacklist.layers.opengl", 3);
user_pref("gfx.blacklist.webgl.angle", 3);
user_pref("gfx.blacklist.webgl.opengl", 3);
user_pref("idle.lastDailyNotification", 1327855096);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1327855097);
user_pref("places.history.expiration.transient_current_max_pages", 10410);
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("privacy.cpd.cookies", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 4);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.migrated", true);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1327716757);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1321196215);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
